# Shared helpers for bootstrap.ps1 and update.ps1. Dot-source this file; do not run it directly.

$ErrorActionPreference = "Stop"

function Assert-SimcoreElevated {
    # LocalSystem is not in the Administrators group, but the runner service uses it
    # and can still install services and change the firewall.
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    $isAdmin = $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin -and -not $identity.IsSystem) {
        throw "Run this from an elevated PowerShell (Administrator). The GitHub runner service must run as LocalSystem."
    }
}

$script:DefaultInstallRoot = "C:\simcore"
$script:DefaultDomain = "157-85-96-139.sslip.io"
$script:DefaultRepoUrl = "https://github.com/nustanakritwithai/Server-Manager-.git"
$script:ServiceIds = @("simcore-api", "simcore-worker", "simcore-caddy")

function New-SimcoreSecret {
    param([int]$Length = 40)
    $alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".ToCharArray()
    $bytes = New-Object byte[] $Length
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }
    $chars = foreach ($b in $bytes) { $alphabet[$b % $alphabet.Length] }
    return -join $chars
}

function Update-SimcorePath {
    $machine = [Environment]::GetEnvironmentVariable("Path", "Machine")
    $user = [Environment]::GetEnvironmentVariable("Path", "User")
    $env:Path = "$machine;$user"
}

function Save-SimcoreDownload {
    param([string]$Url, [string]$Destination)
    $dir = Split-Path -Parent $Destination
    if ($dir) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    Write-Host "Downloading $Url"
    Invoke-WebRequest -Uri $Url -OutFile $Destination -UseBasicParsing
}

function Read-SimcoreEnv {
    param([string]$Path)
    $map = @{}
    if (-not (Test-Path $Path)) { return $map }
    foreach ($line in [System.IO.File]::ReadAllLines($Path)) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#")) { continue }
        $eq = $trimmed.IndexOf("=")
        if ($eq -lt 1) { continue }
        $key = $trimmed.Substring(0, $eq).Trim()
        $value = $trimmed.Substring($eq + 1)
        $map[$key] = $value
    }
    return $map
}

function Write-SimcoreEnv {
    param([string]$Path, [hashtable]$Map)
    $order = @(
        "SIMCORE_ENV",
        "SIMCORE_DATABASE_URL",
        "SIMCORE_ADMIN_TOKEN",
        "SIMCORE_ENABLE_ADMIN",
        "SIMCORE_EMBEDDED_WORKER",
        "SIMCORE_CORS_ORIGINS",
        "SIMCORE_WORKER_POLL_SECONDS",
        "API_DOMAIN",
        "API_PORT",
        "ACME_EMAIL",
        "POSTGRES_SUPER_PASSWORD",
        "SIMCORE_DB_PASSWORD",
        "SIMCORE_INSTALL_ROOT"
    )
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by deploy/windows/bootstrap.ps1. Do not commit this file.")
    foreach ($key in $order) {
        if ($Map.ContainsKey($key)) {
            $lines.Add("$key=$($Map[$key])")
        }
    }
    foreach ($key in ($Map.Keys | Sort-Object)) {
        if ($order -notcontains $key) {
            $lines.Add("$key=$($Map[$key])")
        }
    }
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllLines($Path, $lines, $utf8)
    & icacls $Path /inheritance:r /grant:r "SYSTEM:(R)" "Administrators:(F)" | Out-Null
}

function Import-SimcoreEnvToProcess {
    param([string]$Path)
    $map = Read-SimcoreEnv $Path
    foreach ($key in $map.Keys) {
        [Environment]::SetEnvironmentVariable($key, [string]$map[$key], "Process")
    }
}

function Find-Python312 {
    Update-SimcorePath
    $candidates = @(
        "$env:ProgramFiles\Python312\python.exe",
        "${env:ProgramFiles(x86)}\Python312\python.exe",
        "$env:LocalAppData\Programs\Python\Python312\python.exe"
    )
    foreach ($path in $candidates) {
        if (Test-Path $path) { return $path }
    }
    $cmd = Get-Command python.exe -ErrorAction SilentlyContinue
    if ($cmd -and $cmd.Source) {
        $version = & $cmd.Source -c "import sys; print(f'{sys.version_info[0]}.{sys.version_info[1]}')"
        if ($version -eq "3.12") { return $cmd.Source }
    }
    return $null
}

function Find-Git {
    Update-SimcorePath
    $candidates = @(
        "$env:ProgramFiles\Git\cmd\git.exe",
        "${env:ProgramFiles(x86)}\Git\cmd\git.exe"
    )
    foreach ($path in $candidates) {
        if (Test-Path $path) { return $path }
    }
    $cmd = Get-Command git.exe -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return $null
}

function Find-Psql {
    $roots = Get-ChildItem "$env:ProgramFiles\PostgreSQL" -Directory -ErrorAction SilentlyContinue |
        Sort-Object Name -Descending
    foreach ($root in $roots) {
        $psql = Join-Path $root.FullName "bin\psql.exe"
        if (Test-Path $psql) { return $psql }
    }
    return $null
}

function Find-PostgresLayout {
    $psql = Find-Psql
    if (-not $psql) { return $null }
    $root = Split-Path (Split-Path $psql -Parent) -Parent
    $service = Get-Service -ErrorAction SilentlyContinue | Where-Object { $_.Name -like "postgresql*" } |
        Sort-Object Name -Descending |
        Select-Object -First 1
    return @{
        Psql = $psql
        Root = $root
        Data = Join-Path $root "data"
        ServiceName = $(if ($service) { $service.Name } else { $null })
    }
}

function Install-WithWinget {
    param([string]$Id, [string]$Override = "")
    $winget = Get-Command winget.exe -ErrorAction SilentlyContinue
    if (-not $winget) { return $false }
    Write-Host "winget install $Id"
    $args = @(
        "install", "--id", $Id, "-e",
        "--accept-package-agreements", "--accept-source-agreements",
        "--disable-interactivity"
    )
    if ($Override) { $args += @("--override", $Override) }
    & winget.exe @args
    # 0 = installed. -1978335189 = no update / already installed.
    if ($LASTEXITCODE -eq 0 -or $LASTEXITCODE -eq -1978335189) { return $true }
    Write-Warning "winget exit $LASTEXITCODE for $Id"
    return $false
}

function Ensure-Git {
    if (Find-Git) { return }
    Install-WithWinget -Id "Git.Git" | Out-Null
    Update-SimcorePath
    if (Find-Git) { return }
    throw "Git is not installed and winget could not install Git.Git. Install Git for Windows, reopen PowerShell, and run bootstrap again."
}

function Ensure-Python {
    if (Find-Python312) { return }
    Install-WithWinget -Id "Python.Python.3.12" | Out-Null
    Update-SimcorePath
    if (Find-Python312) { return }
    $installer = Join-Path $env:TEMP "python-3.12.10-amd64.exe"
    Save-SimcoreDownload "https://www.python.org/ftp/python/3.12.10/python-3.12.10-amd64.exe" $installer
    $proc = Start-Process -FilePath $installer -ArgumentList @(
        "/quiet", "InstallAllUsers=1", "PrependPath=1", "Include_test=0", "Include_pip=1"
    ) -Wait -PassThru
    if ($proc.ExitCode -ne 0 -and $proc.ExitCode -ne 3010) {
        throw "Python installer failed with exit code $($proc.ExitCode)"
    }
    Update-SimcorePath
    if (-not (Find-Python312)) { throw "Python 3.12 installed but python.exe was not found." }
}

function Ensure-Caddy {
    param([string]$InstallRoot)
    $dest = Join-Path $InstallRoot "tools\caddy.exe"
    if (Test-Path $dest) { return $dest }
    $zip = Join-Path $env:TEMP "caddy_2.11.7_windows_amd64.zip"
    $extract = Join-Path $env:TEMP "caddy-extract"
    Save-SimcoreDownload "https://github.com/caddyserver/caddy/releases/download/v2.11.7/caddy_2.11.7_windows_amd64.zip" $zip
    if (Test-Path $extract) { Remove-Item $extract -Recurse -Force }
    Expand-Archive -Path $zip -DestinationPath $extract -Force
    $found = Get-ChildItem $extract -Filter "caddy.exe" -Recurse | Select-Object -First 1
    if (-not $found) { throw "caddy.exe was not in the zip" }
    New-Item -ItemType Directory -Force -Path (Split-Path $dest) | Out-Null
    Copy-Item $found.FullName $dest -Force
    return $dest
}

function Ensure-WinSW {
    param([string]$InstallRoot)
    $dest = Join-Path $InstallRoot "tools\WinSW.NET4.exe"
    if (-not (Test-Path $dest)) {
        Save-SimcoreDownload "https://github.com/winsw/winsw/releases/download/v2.12.0/WinSW.NET4.exe" $dest
    }
    return $dest
}

function Ensure-PostgresInstalled {
    param([string]$SuperPassword)
    if (Find-Psql) { return }
    $override = "--mode unattended --unattendedmodeui none --superpassword $SuperPassword --serverport 5432 --enable-components server,commandlinetools"
    Install-WithWinget -Id "PostgreSQL.PostgreSQL.16" -Override $override | Out-Null
    Update-SimcorePath
    if (Find-Psql) { return }
    $installer = Join-Path $env:TEMP "postgresql-16.15-5-windows-x64.exe"
    Save-SimcoreDownload "https://get.enterprisedb.com/postgresql/postgresql-16.15-5-windows-x64.exe" $installer
    $proc = Start-Process -FilePath $installer -ArgumentList @(
        "--mode", "unattended",
        "--unattendedmodeui", "none",
        "--superpassword", $SuperPassword,
        "--serverport", "5432",
        "--enable-components", "server,commandlinetools"
    ) -Wait -PassThru
    if ($proc.ExitCode -ne 0 -and $proc.ExitCode -ne 3010) {
        throw "PostgreSQL installer failed with exit code $($proc.ExitCode). Log: $env:TEMP\install-postgresql.log"
    }
    Update-SimcorePath
    if (-not (Find-Psql)) { throw "PostgreSQL installed but psql.exe was not found." }
}

function Set-PostgresListenLocalhost {
    param([string]$DataDir)
    $conf = Join-Path $DataDir "postgresql.conf"
    if (-not (Test-Path $conf)) { throw "postgresql.conf not found at $conf" }
    $lines = [System.Collections.Generic.List[string]]::new()
    $found = $false
    foreach ($line in [System.IO.File]::ReadAllLines($conf)) {
        if ($line -match '^\s*#?\s*listen_addresses\s*=') {
            if (-not $found) { $lines.Add("listen_addresses = 'localhost'") }
            $found = $true
        } else {
            $lines.Add($line)
        }
    }
    if (-not $found) { $lines.Add("listen_addresses = 'localhost'") }
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllLines($conf, $lines, $utf8)
}

function Disable-PublicPostgres {
    $named = Get-NetFirewallRule -ErrorAction SilentlyContinue | Where-Object {
        $_.DisplayName -match 'PostgreSQL|postgres'
    }
    foreach ($rule in $named) {
        Disable-NetFirewallRule -Name $rule.Name
        Write-Host "Disabled firewall rule: $($rule.DisplayName)"
    }
    $inbound = Get-NetFirewallRule -Direction Inbound -Action Allow -ErrorAction SilentlyContinue
    foreach ($rule in $inbound) {
        $filter = $rule | Get-NetFirewallPortFilter -ErrorAction SilentlyContinue
        $ports = @($filter.LocalPort)
        if ($ports -contains 5432 -or $ports -contains "5432") {
            Disable-NetFirewallRule -Name $rule.Name
            Write-Host "Disabled inbound 5432 rule: $($rule.DisplayName)"
        }
    }
}

function Enable-WebFirewall {
    foreach ($spec in @(
        @{ Name = "Simcore HTTP (80)"; Port = 80 },
        @{ Name = "Simcore HTTPS (443)"; Port = 443 }
    )) {
        $existing = Get-NetFirewallRule -DisplayName $spec.Name -ErrorAction SilentlyContinue
        if (-not $existing) {
            New-NetFirewallRule -DisplayName $spec.Name -Direction Inbound -Action Allow -Protocol TCP -LocalPort $spec.Port | Out-Null
            Write-Host "Opened TCP $($spec.Port)"
        } else {
            Enable-NetFirewallRule -DisplayName $spec.Name
        }
    }
}

function Stop-SiteBindings {
    $iis = Get-Service -Name "W3SVC" -ErrorAction SilentlyContinue
    if ($iis) {
        if ($iis.Status -ne "Stopped") {
            Write-Host "Stopping IIS (W3SVC) so Caddy can listen on 80 and 443"
            Stop-Service -Name "W3SVC" -Force
        }
        Set-Service -Name "W3SVC" -StartupType Disabled
    }
}

function Assert-PostgresLocalOnly {
    $listeners = @(Get-NetTCPConnection -LocalPort 5432 -State Listen -ErrorAction SilentlyContinue)
    if (-not $listeners) {
        throw "PostgreSQL is not listening on port 5432."
    }
    foreach ($listener in $listeners) {
        $address = [string]$listener.LocalAddress
        if ($address -notin @("127.0.0.1", "::1")) {
            throw "PostgreSQL is listening on ${address}:5432. It must stay on localhost."
        }
    }
}

function Invoke-Psql {
    param(
        [string]$Psql,
        [string]$Database = "postgres",
        [string]$Command,
        [hashtable]$Variables
    )
    # -w fails instead of prompting if the password is wrong, so the script cannot hang on a password prompt.
    $args = @("-w", "-U", "postgres", "-h", "127.0.0.1", "-d", $Database, "-v", "ON_ERROR_STOP=1", "-tA")
    if ($Variables) {
        foreach ($key in $Variables.Keys) {
            $args += @("-v", "${key}=$($Variables[$key])")
        }
    }
    if ($Command) { $args += @("-c", $Command) }
    $output = & $Psql @args
    if ($LASTEXITCODE -ne 0) { throw "psql failed: $Command" }
    return $output
}

function Test-PostgresLogin {
    param([string]$Psql, [string]$Password)
    $previous = $env:PGPASSWORD
    $env:PGPASSWORD = $Password
    & $Psql -w -U postgres -h 127.0.0.1 -d postgres -c "SELECT 1" | Out-Null
    $ok = ($LASTEXITCODE -eq 0)
    if ($null -ne $previous) { $env:PGPASSWORD = $previous } else { Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue }
    return $ok
}

function Initialize-SimcoreDatabase {
    param([string]$Psql, [hashtable]$EnvMap)
    $super = $EnvMap["POSTGRES_SUPER_PASSWORD"]
    $dbPass = $EnvMap["SIMCORE_DB_PASSWORD"]
    if (-not (Test-PostgresLogin -Psql $Psql -Password $super)) {
        if (Test-PostgresLogin -Psql $Psql -Password "postgres") {
            $env:PGPASSWORD = "postgres"
            Invoke-Psql -Psql $Psql -Command "ALTER ROLE postgres WITH PASSWORD :'simpass';" -Variables @{ simpass = $super } | Out-Null
            Write-Host "Rotated the postgres superuser password away from the installer default."
        } else {
            throw "Could not sign in as postgres. Set POSTGRES_SUPER_PASSWORD in .env.prod to the current password and run bootstrap again."
        }
    }
    $env:PGPASSWORD = $super
    $role = [string](Invoke-Psql -Psql $Psql -Command "SELECT 1 FROM pg_roles WHERE rolname = 'simcore'")
    if ($role.Trim() -eq "1") {
        Invoke-Psql -Psql $Psql -Command "ALTER ROLE simcore WITH LOGIN PASSWORD :'simpass';" -Variables @{ simpass = $dbPass } | Out-Null
    } else {
        Invoke-Psql -Psql $Psql -Command "CREATE ROLE simcore LOGIN PASSWORD :'simpass';" -Variables @{ simpass = $dbPass } | Out-Null
    }
    $db = [string](Invoke-Psql -Psql $Psql -Command "SELECT 1 FROM pg_database WHERE datname = 'simcore'")
    if ($db -notmatch "1") {
        Invoke-Psql -Psql $Psql -Command "CREATE DATABASE simcore OWNER simcore;" | Out-Null
    }
    Invoke-Psql -Psql $Psql -Database "simcore" -Command "ALTER SCHEMA public OWNER TO simcore;" | Out-Null
}

function Write-SimcoreCaddyfile {
    param([hashtable]$EnvMap, [string]$InstallRoot)
    $domain = $EnvMap["API_DOMAIN"]
    if (-not $domain) { throw "API_DOMAIN is missing from .env.prod" }
    $port = $EnvMap["API_PORT"]
    if (-not $port) { $port = "8741" }
    $email = $EnvMap["ACME_EMAIL"]
    $emailLine = ""
    if ($email) { $emailLine = "    email $email`r`n" }
    $data = ($InstallRoot + "\caddy-data") -replace "\\", "/"
    $body = @"
{
    storage file_system {
        root $data
    }
$emailLine}

$domain {
    encode gzip
    reverse_proxy 127.0.0.1:$port
}
"@
    $path = Join-Path $InstallRoot "Caddyfile"
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($path, $body.Trim() + "`r`n", $utf8)
    return $path
}

function Write-WinSwServiceXml {
    param(
        [string]$XmlPath,
        [string]$Id,
        [string]$DisplayName,
        [string]$Description,
        [string]$Executable,
        [string]$Arguments,
        [string]$WorkingDirectory,
        [string]$LogDir,
        [string]$Depend = ""
    )
    $dependXml = ""
    if ($Depend) { $dependXml = "  <depend>$([System.Security.SecurityElement]::Escape($Depend))</depend>`r`n" }
    $xml = @"
<service>
  <id>$Id</id>
  <name>$([System.Security.SecurityElement]::Escape($DisplayName))</name>
  <description>$([System.Security.SecurityElement]::Escape($Description))</description>
  <executable>$([System.Security.SecurityElement]::Escape($Executable))</executable>
  <arguments>$([System.Security.SecurityElement]::Escape($Arguments))</arguments>
  <workingdirectory>$([System.Security.SecurityElement]::Escape($WorkingDirectory))</workingdirectory>
  <env name="PYTHONUNBUFFERED" value="1" />
  <env name="SIMCORE_ENV" value="production" />
$dependXml  <logpath>$([System.Security.SecurityElement]::Escape($LogDir))</logpath>
  <log mode="roll-by-size">
    <sizeThreshold>10240</sizeThreshold>
    <keepFiles>8</keepFiles>
  </log>
  <onfailure action="restart" delay="5 sec" />
  <onfailure action="restart" delay="15 sec" />
  <onfailure action="restart" delay="30 sec" />
  <resetfailure>1 hour</resetfailure>
  <startmode>Automatic</startmode>
  <delayedAutoStart>true</delayedAutoStart>
  <stoptimeout>20 sec</stoptimeout>
</service>
"@
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($XmlPath, $xml.Trim() + "`r`n", $utf8)
}

function Install-SimcoreWindowsServices {
    param(
        [string]$RepoRoot,
        [string]$InstallRoot,
        [hashtable]$EnvMap,
        [switch]$Reinstall
    )
    $winsw = Ensure-WinSW -InstallRoot $InstallRoot
    $caddy = Join-Path $InstallRoot "tools\caddy.exe"
    $python = Join-Path $RepoRoot ".venv\Scripts\python.exe"
    $port = $EnvMap["API_PORT"]
    if (-not $port) { $port = "8741" }
    $layout = Find-PostgresLayout
    $depend = ""
    if ($layout -and $layout.ServiceName) { $depend = $layout.ServiceName }
    $logDir = Join-Path $InstallRoot "logs"
    $caddyFile = Join-Path $InstallRoot "Caddyfile"
    $servicesDir = Join-Path $InstallRoot "services"
    New-Item -ItemType Directory -Force -Path $servicesDir, $logDir | Out-Null

    $specs = @(
        @{
            Id = "simcore-api"
            Name = "Simcore API"
            Description = "Strategy game simulation API (localhost only; Caddy publishes HTTPS)"
            Executable = $python
            Arguments = "-m uvicorn simcore.main:app --host 127.0.0.1 --port $port"
            Depend = $depend
        },
        @{
            Id = "simcore-worker"
            Name = "Simcore Worker"
            Description = "Claims due world events with SKIP LOCKED"
            Executable = $python
            Arguments = "-m simcore.worker"
            Depend = $depend
        },
        @{
            Id = "simcore-caddy"
            Name = "Simcore Caddy"
            Description = "HTTPS reverse proxy and Let's Encrypt for the game API"
            Executable = $caddy
            Arguments = "run --config " + ($caddyFile -replace '\\', '/')
            Depend = ""
        }
    )

    foreach ($spec in $specs) {
        $exe = Join-Path $servicesDir "$($spec.Id).exe"
        $xml = Join-Path $servicesDir "$($spec.Id).xml"
        $installed = Get-Service -Name $spec.Id -ErrorAction SilentlyContinue
        if ($installed -and $installed.Status -ne "Stopped") {
            Stop-Service -Name $spec.Id -Force
        }
        if ($installed -and $Reinstall -and (Test-Path $exe)) {
            & $exe uninstall | Out-Null
            Start-Sleep -Seconds 1
            $installed = $null
        }
        Write-WinSwServiceXml -XmlPath $xml -Id $spec.Id -DisplayName $spec.Name -Description $spec.Description `
            -Executable $spec.Executable -Arguments $spec.Arguments -WorkingDirectory $RepoRoot `
            -LogDir $logDir -Depend $spec.Depend
        Copy-Item $winsw $exe -Force
        if (-not $installed) {
            & $exe install
            if ($LASTEXITCODE -ne 0) { throw "Could not install Windows service $($spec.Id)" }
            & sc.exe @("failure", $spec.Id, "reset=", "86400", "actions=", "restart/5000/restart/15000/restart/30000") | Out-Null
        }
    }
}

function Stop-SimcoreStack {
    foreach ($id in @("simcore-caddy", "simcore-worker", "simcore-api")) {
        $svc = Get-Service -Name $id -ErrorAction SilentlyContinue
        if ($svc -and $svc.Status -ne "Stopped") {
            Write-Host "Stopping $id"
            Stop-Service -Name $id -Force
        }
    }
}

function Start-SimcoreStack {
    foreach ($id in @("simcore-api", "simcore-worker", "simcore-caddy")) {
        $svc = Get-Service -Name $id -ErrorAction SilentlyContinue
        if (-not $svc) { throw "Windows service $id is not installed. Run deploy\windows\bootstrap.ps1 first." }
        Write-Host "Starting $id"
        Start-Service -Name $id
    }
}

function Wait-SimcoreApi {
    param([string]$Port = "8741")
    if (-not $Port) { $Port = "8741" }
    $url = "http://127.0.0.1:$Port/health/ready"
    for ($i = 1; $i -le 30; $i++) {
        try {
            $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 3
            if ($response.StatusCode -eq 200) {
                Write-Host "API is ready at $url"
                return
            }
        } catch {
            Write-Host "Waiting for the API ($i/30)"
        }
        Start-Sleep -Seconds 2
    }
    throw "The API did not become ready at $url. Check C:\simcore\logs."
}

function Ensure-Repo {
    param([string]$RepoRoot, [string]$RepoUrl)
    if (Test-Path (Join-Path $RepoRoot ".git")) { return }
    if (Test-Path $RepoRoot) { throw "$RepoRoot exists but is not a git checkout." }
    $parent = Split-Path -Parent $RepoRoot
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
    $git = Find-Git
    & $git clone $RepoUrl $RepoRoot
    if ($LASTEXITCODE -ne 0) { throw "git clone failed" }
}

function Ensure-Venv {
    param([string]$RepoRoot)
    $python = Find-Python312
    if (-not $python) { throw "Python 3.12 is not installed." }
    $venvPython = Join-Path $RepoRoot ".venv\Scripts\python.exe"
    if (-not (Test-Path $venvPython)) {
        & $python -m venv (Join-Path $RepoRoot ".venv")
        if ($LASTEXITCODE -ne 0) { throw "Could not create the virtualenv" }
    }
    & $venvPython -m pip install --upgrade pip
    if ($LASTEXITCODE -ne 0) { throw "pip upgrade failed" }
    & $venvPython -m pip install -e $RepoRoot
    if ($LASTEXITCODE -ne 0) { throw "pip install -e . failed" }
}

function Invoke-SimcoreMigrations {
    param([string]$RepoRoot)
    $python = Join-Path $RepoRoot ".venv\Scripts\python.exe"
    Push-Location $RepoRoot
    try {
        & $python -m alembic upgrade head
        if ($LASTEXITCODE -ne 0) { throw "alembic upgrade head failed" }
        & $python -m simcore.seed
        if ($LASTEXITCODE -ne 0) { throw "seed failed" }
    } finally {
        Pop-Location
    }
}

function Invoke-SimcoreGitPull {
    param([string]$RepoRoot)
    $git = Find-Git
    if (-not $git) { throw "git.exe was not found. Run bootstrap.ps1 once." }
    $safe = @(& $git config --global --get-all safe.directory 2>$null)
    if (@($safe) -notcontains $RepoRoot) {
        & $git config --global --add safe.directory $RepoRoot
    }
    & $git -C $RepoRoot fetch origin main
    if ($LASTEXITCODE -ne 0) { throw "git fetch origin main failed" }
    & $git -C $RepoRoot checkout main
    if ($LASTEXITCODE -ne 0) { throw "git checkout main failed" }
    & $git -C $RepoRoot pull --ff-only origin main
    if ($LASTEXITCODE -ne 0) { throw "git pull --ff-only origin main failed" }
}

function New-SimcoreProductionEnv {
    param(
        [string]$Path,
        [string]$InstallRoot,
        [string]$ApiDomain,
        [string]$ApiPort,
        [string]$AcmeEmail
    )
    if (Test-Path $Path) {
        return Read-SimcoreEnv $Path
    }
    $super = New-SimcoreSecret
    $dbPass = New-SimcoreSecret
    $admin = New-SimcoreSecret
    $urlPass = [uri]::EscapeDataString($dbPass)
    $map = @{
        SIMCORE_ENV = "production"
        SIMCORE_DATABASE_URL = "postgresql+psycopg://simcore:${urlPass}@127.0.0.1:5432/simcore"
        SIMCORE_ADMIN_TOKEN = $admin
        SIMCORE_ENABLE_ADMIN = "false"
        SIMCORE_EMBEDDED_WORKER = "false"
        SIMCORE_CORS_ORIGINS = "https://nustanakritwithai.github.io,http://127.0.0.1:8080,http://localhost:8080"
        SIMCORE_WORKER_POLL_SECONDS = "1.0"
        API_DOMAIN = $ApiDomain
        API_PORT = $ApiPort
        ACME_EMAIL = $AcmeEmail
        POSTGRES_SUPER_PASSWORD = $super
        SIMCORE_DB_PASSWORD = $dbPass
        SIMCORE_INSTALL_ROOT = $InstallRoot
    }
    Write-SimcoreEnv -Path $Path -Map $map
    Write-Host "Wrote $Path"
    Write-Host "The database password and admin token were generated into that file. They are not printed here."
    return $map
}
