from functools import lru_cache

from pydantic import field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from simcore.runtime_secrets import player_token_secret_is_usable

# Browser origins used when trying the static client against a local API.
# Production does not add these on its own; put them in SIMCORE_CORS_ORIGINS
# only if you want a laptop on the same machine to call the public API.
LOCAL_DEV_ORIGINS = (
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:5500",
    "http://127.0.0.1:5500",
    "http://localhost:4173",
    "http://127.0.0.1:4173",
    "http://localhost:8741",
    "http://127.0.0.1:8741",
)

# GitHub Pages origin for https://nustanakritwithai.github.io/Server-Manager-/
# The path is not part of the origin.
GITHUB_PAGES_ORIGIN = "https://nustanakritwithai.github.io"

# Tokens that must never authenticate admin routes on a public server.
_FORBIDDEN_PRODUCTION_TOKENS = frozenset({"", "dev-admin", "change_me", "changeme"})


def normalize_database_url(value: str) -> str:
    """Accept postgres:// and postgresql:// URLs and use the psycopg driver.

    Hosted Postgres often hands out a libpq URL. SQLAlchemy needs the driver
    name in the scheme or it tries to import psycopg2.
    """

    stripped = value.strip()
    lowered = stripped.lower()
    if lowered.startswith("postgresql+"):
        return stripped
    if lowered.startswith("postgres://"):
        return "postgresql+psycopg://" + stripped[len("postgres://") :]
    if lowered.startswith("postgresql://"):
        return "postgresql+psycopg://" + stripped[len("postgresql://") :]
    return stripped


class Settings(BaseSettings):
    """Runtime settings. Environment variables use the SIMCORE_ prefix."""

    model_config = SettingsConfigDict(
        env_prefix="SIMCORE_",
        env_file=(".env", ".env.prod"),
        env_file_encoding="utf-8",
        extra="ignore",
    )

    database_url: str = "postgresql+psycopg://simcore:simcore@127.0.0.1:5432/simcore"
    env: str = "development"
    admin_token: str = "dev-admin"
    enable_admin: bool = False
    # scrypt hash from deploy/windows/set-admin-password.ps1. Never a plaintext password.
    admin_password_hash: str = ""
    # HMAC key for admin session tokens. Generated by the same script when missing.
    admin_session_secret: str = ""
    # About 30 days. The admin page shows the resulting expiry.
    admin_session_ttl_seconds: int = 30 * 24 * 60 * 60
    # Increase this and restart the API to invalidate every session token.
    admin_session_version: int = 1
    admin_login_max_failures: int = 8
    admin_login_window_seconds: int = 15 * 60
    # HMAC key for player access tokens. Bootstrap and update.ps1 generate it.
    # The development default is rejected when SIMCORE_ENV=production.
    player_token_secret: str = "dev-player-token-secret-not-for-production"
    player_access_ttl_seconds: int = 15 * 60
    player_refresh_ttl_seconds: int = 30 * 24 * 60 * 60
    # Off unless SIMCORE_ENV is dev/development/test/testing, or this is true.
    enable_dev_login: bool = False
    player_login_max_failures: int = 5
    player_login_ip_max_failures: int = 20
    player_login_window_seconds: int = 15 * 60
    player_login_lockout_seconds: int = 15 * 60
    command_rate_limit: int = 30
    command_rate_window_seconds: int = 60
    worker_poll_seconds: float = 1.0
    max_event_attempts: int = 5
    # Comma-separated browser origins. The Windows bootstrap writes this.
    cors_origins: str = ",".join((GITHUB_PAGES_ORIGIN, *LOCAL_DEV_ORIGINS))
    # When true, the API process also runs the worker loop. The standalone
    # worker remains the default, including on the Windows VPS.
    embedded_worker: bool = False
    # Monitoring. Every value below is optional. Unset means the default.
    # Sample interval 0 turns periodic samples off. Otherwise it is 10 to 3600 seconds.
    monitor_sample_seconds: float = 60
    monitor_retention_days: int = 7
    # The API process also writes samples so API latency history exists while
    # the API is up. Tests set this false. The worker loop samples either way.
    monitor_api_sampler: bool = True
    # Empty measures the drive of the process working directory (C:\ on the VPS
    # when the app lives on C:, / in a Linux container). A missing path is
    # reported NOT INSTRUMENTED, not as a healthy disk.
    monitor_disk_path: str = ""
    monitor_heartbeat_warn_seconds: float = 15
    monitor_heartbeat_critical_seconds: float = 60
    monitor_event_lag_warn_seconds: float = 15
    monitor_event_lag_critical_seconds: float = 120
    monitor_oldest_due_warn_seconds: float = 15
    monitor_oldest_due_critical_seconds: float = 120
    monitor_queue_pending_warn: int = 500
    monitor_queue_pending_critical: int = 5000
    monitor_queue_due_warn: int = 25
    monitor_queue_due_critical: int = 200
    monitor_failed_warn: int = 1
    monitor_failed_critical: int = 10
    monitor_retried_warn: int = 1
    monitor_retried_critical: int = 20
    monitor_processing_warn_seconds: float = 30
    monitor_processing_critical_seconds: float = 120
    monitor_api_error_rate_warn: float = 0.01
    monitor_api_error_rate_critical: float = 0.05
    monitor_api_5xx_warn: int = 1
    monitor_api_5xx_critical: int = 10
    monitor_api_p95_warn_ms: float = 300
    monitor_api_p95_critical_ms: float = 1000
    monitor_db_rtt_warn_ms: float = 50
    monitor_db_rtt_critical_ms: float = 200
    monitor_db_pool_warn: float = 0.8
    monitor_db_pool_critical: float = 0.95
    monitor_db_size_warn_mb: int = 10240
    monitor_db_size_critical_mb: int = 40960
    monitor_disk_free_warn_mb: int = 5120
    monitor_disk_free_critical_mb: int = 2048
    # Host percents are higher-is-worse. A saturated sample can reach these
    # bars. A failed reading is UNKNOWN, not a fake zero.
    # SIMCORE_MONITOR_CPU_WARN_PERCENT / SIMCORE_MONITOR_CPU_CRITICAL_PERCENT
    # SIMCORE_MONITOR_MEMORY_WARN_PERCENT / SIMCORE_MONITOR_MEMORY_CRITICAL_PERCENT
    monitor_cpu_warn_percent: float = 90
    monitor_cpu_critical_percent: float = 98
    monitor_memory_warn_percent: float = 85
    monitor_memory_critical_percent: float = 95
    # Off-site backup status written by deploy/windows/backup.ps1.
    # Empty uses C:\simcore\backups\backup-status.json on Windows, and is
    # UNKNOWN elsewhere until SIMCORE_BACKUP_STATUS_PATH is set.
    backup_status_path: str = ""
    backup_warn_hours: float = 26
    backup_critical_hours: float = 50

    @field_validator("database_url", mode="before")
    @classmethod
    def _normalize_database_url(cls, value: object) -> object:
        if isinstance(value, str):
            return normalize_database_url(value)
        return value

    @model_validator(mode="after")
    def _production_admin_token(self) -> "Settings":
        if self.env == "production":
            token = self.admin_token.strip()
            if token.casefold() in _FORBIDDEN_PRODUCTION_TOKENS:
                raise ValueError(
                    "SIMCORE_ADMIN_TOKEN must be set to a unique value when SIMCORE_ENV=production. "
                    "dev-admin is only for local docker-compose."
                )
            self.admin_token = token
        self.admin_password_hash = self.admin_password_hash.strip()
        self.admin_session_secret = self.admin_session_secret.strip()
        if self.admin_session_ttl_seconds < 60:
            raise ValueError("SIMCORE_ADMIN_SESSION_TTL_SECONDS must be at least 60")
        if self.admin_session_version < 0:
            raise ValueError("SIMCORE_ADMIN_SESSION_VERSION must be zero or greater")
        if self.admin_login_max_failures < 1:
            raise ValueError("SIMCORE_ADMIN_LOGIN_MAX_FAILURES must be at least 1")
        if self.admin_login_window_seconds < 1:
            raise ValueError("SIMCORE_ADMIN_LOGIN_WINDOW_SECONDS must be at least 1")
        self.player_token_secret = self.player_token_secret.strip()
        if self.env == "production" and not player_token_secret_is_usable(
            self.player_token_secret, production=True
        ):
            raise ValueError(
                "SIMCORE_PLAYER_TOKEN_SECRET must be a unique random value of at least 32 characters "
                "when SIMCORE_ENV=production. deploy/windows/update.ps1 writes one into .env.prod when it is missing."
            )
        if self.player_access_ttl_seconds < 60:
            raise ValueError("SIMCORE_PLAYER_ACCESS_TTL_SECONDS must be at least 60")
        if self.player_refresh_ttl_seconds < self.player_access_ttl_seconds:
            raise ValueError("SIMCORE_PLAYER_REFRESH_TTL_SECONDS must be at least the access token lifetime")
        if self.player_login_max_failures < 1:
            raise ValueError("SIMCORE_PLAYER_LOGIN_MAX_FAILURES must be at least 1")
        if self.player_login_ip_max_failures < 1:
            raise ValueError("SIMCORE_PLAYER_LOGIN_IP_MAX_FAILURES must be at least 1")
        if self.player_login_window_seconds < 1 or self.player_login_lockout_seconds < 1:
            raise ValueError("SIMCORE_PLAYER_LOGIN window and lockout must be at least 1 second")
        if self.command_rate_limit < 1 or self.command_rate_window_seconds < 1:
            raise ValueError("SIMCORE_COMMAND_RATE_LIMIT and SIMCORE_COMMAND_RATE_WINDOW_SECONDS must be at least 1")
        self._check_monitor()
        return self

    @property
    def dev_login_enabled(self) -> bool:
        """Placeholder dev-login. Production stays off unless SIMCORE_ENABLE_DEV_LOGIN=true."""

        if self.enable_dev_login:
            return True
        return self.env.strip().lower() in {"dev", "development", "test", "testing"}

    def _check_monitor(self) -> None:
        if self.monitor_sample_seconds < 0:
            raise ValueError("SIMCORE_MONITOR_SAMPLE_SECONDS must be 0 (off) or at least 10")
        if self.monitor_sample_seconds != 0 and not 10 <= self.monitor_sample_seconds <= 3600:
            raise ValueError("SIMCORE_MONITOR_SAMPLE_SECONDS must be 0 (off) or between 10 and 3600")
        if not 1 <= self.monitor_retention_days <= 30:
            raise ValueError("SIMCORE_MONITOR_RETENTION_DAYS must be from 1 to 30")
        self.monitor_disk_path = self.monitor_disk_path.strip()
        pairs = (
            ("SIMCORE_MONITOR_HEARTBEAT", self.monitor_heartbeat_warn_seconds, self.monitor_heartbeat_critical_seconds),
            ("SIMCORE_MONITOR_EVENT_LAG", self.monitor_event_lag_warn_seconds, self.monitor_event_lag_critical_seconds),
            ("SIMCORE_MONITOR_OLDEST_DUE", self.monitor_oldest_due_warn_seconds, self.monitor_oldest_due_critical_seconds),
            ("SIMCORE_MONITOR_QUEUE_PENDING", self.monitor_queue_pending_warn, self.monitor_queue_pending_critical),
            ("SIMCORE_MONITOR_QUEUE_DUE", self.monitor_queue_due_warn, self.monitor_queue_due_critical),
            ("SIMCORE_MONITOR_FAILED", self.monitor_failed_warn, self.monitor_failed_critical),
            ("SIMCORE_MONITOR_RETRIED", self.monitor_retried_warn, self.monitor_retried_critical),
            ("SIMCORE_MONITOR_PROCESSING", self.monitor_processing_warn_seconds, self.monitor_processing_critical_seconds),
            ("SIMCORE_MONITOR_API_ERROR_RATE", self.monitor_api_error_rate_warn, self.monitor_api_error_rate_critical),
            ("SIMCORE_MONITOR_API_5XX", self.monitor_api_5xx_warn, self.monitor_api_5xx_critical),
            ("SIMCORE_MONITOR_API_P95", self.monitor_api_p95_warn_ms, self.monitor_api_p95_critical_ms),
            ("SIMCORE_MONITOR_DB_RTT", self.monitor_db_rtt_warn_ms, self.monitor_db_rtt_critical_ms),
            ("SIMCORE_MONITOR_DB_POOL", self.monitor_db_pool_warn, self.monitor_db_pool_critical),
            ("SIMCORE_MONITOR_DB_SIZE_MB", self.monitor_db_size_warn_mb, self.monitor_db_size_critical_mb),
            ("SIMCORE_MONITOR_CPU_PERCENT", self.monitor_cpu_warn_percent, self.monitor_cpu_critical_percent),
            ("SIMCORE_MONITOR_MEMORY_PERCENT", self.monitor_memory_warn_percent, self.monitor_memory_critical_percent),
        )
        for name, warn, critical in pairs:
            if warn < 0 or critical < 0:
                raise ValueError(f"{name} warn and critical must be zero or greater")
            if warn >= critical:
                raise ValueError(f"{name} warn must be below critical")
        if self.monitor_disk_free_warn_mb <= 0 or self.monitor_disk_free_critical_mb <= 0:
            raise ValueError("SIMCORE_MONITOR_DISK_FREE warn and critical must be greater than zero")
        if self.monitor_disk_free_warn_mb <= self.monitor_disk_free_critical_mb:
            raise ValueError("SIMCORE_MONITOR_DISK_FREE_WARN_MB must be above SIMCORE_MONITOR_DISK_FREE_CRITICAL_MB")
        self.backup_status_path = self.backup_status_path.strip()
        if self.backup_warn_hours <= 0 or self.backup_critical_hours <= 0:
            raise ValueError("SIMCORE_BACKUP_WARN_HOURS and SIMCORE_BACKUP_CRITICAL_HOURS must be greater than zero")
        if self.backup_warn_hours >= self.backup_critical_hours:
            raise ValueError("SIMCORE_BACKUP_WARN_HOURS must be below SIMCORE_BACKUP_CRITICAL_HOURS")

    @property
    def monitor_disk_free_warn_bytes(self) -> int:
        return self.monitor_disk_free_warn_mb * 1024 * 1024

    @property
    def monitor_disk_free_critical_bytes(self) -> int:
        return self.monitor_disk_free_critical_mb * 1024 * 1024

    @property
    def monitor_db_size_warn_bytes(self) -> int:
        return self.monitor_db_size_warn_mb * 1024 * 1024

    @property
    def monitor_db_size_critical_bytes(self) -> int:
        return self.monitor_db_size_critical_mb * 1024 * 1024

    @property
    def admin_enabled(self) -> bool:
        if self.env == "production":
            return self.enable_admin
        return True

    @property
    def cors_origin_list(self) -> list[str]:
        origins: list[str] = []
        for part in self.cors_origins.split(","):
            item = part.strip()
            if item and item not in origins:
                origins.append(item)
        if self.env != "production":
            for item in LOCAL_DEV_ORIGINS:
                if item not in origins:
                    origins.append(item)
        return origins


@lru_cache
def get_settings() -> Settings:
    return Settings()
